apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icestream.fullname" . }}-executor-pod-template
  labels:
    {{- include "icestream.labels" . | nindent 4 }}
data:
  executor-pod-template.yaml: |
    apiVersion: v1
    kind: Pod
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "icestream.serviceAccountName" . }}
      containers:
        - name: spark-kubernetes-executor
          env:
            - name: SPARK_LOCAL_DIRS
              value: {{ .Values.spark.scratchDir }}
